#!/bin/bash
#
# Docker Functions

alias dps='docker ps -a'
alias drm='docker rm $1'
alias dst='docker stop $1'

function dconfig() {
	docker network create xdc.pw
}

function dbash() {
	docker exec -it \
		"$1" /bin/bash
}

function dkali() {
	DOTS="${HOME}"/.dotfiles

	docker exec -it kali.d /bin/bash || \
	docker run -ti \
		--name kali.d \
		--hostname kali \
		-v "${HOME}"/data:/data \
		-v /var/run/docker.sock:/var/run/docker.sock:ro \
		-v "${DOTS}"/config:/root/.config \
		-v "${DOTS}"/bash_colors.sh:/root/.bash_colors.sh \
		-v "${DOTS}"/nanorc:/etc/nanorc:ro \
		-v "${DOTS}"/bash.d:/root/.bash.d \
		-v "${DOTS}"/functions.d:/root/.functions.d \
		-v "${DOTS}"/scripts:/root/.scripts \
		-v "${DOTS}"/bashrc:/root/.bashrc \
		-v "${DOTS}"/profile:/root/.profile \
		kalilinux/kali-rolling
}
